### ISSUE TITLE
GridField buttons disappear when this module is installed

### ISSUE THREAD

**Issue by elkebe** [goldfinch/image-editor#1]
Affects SS5.2, php 8.1-8.3

Steps to reproduce:

- install goldfinch/image-editor using composer
- login to admin > Security (or any other model admin)
- grid field buttons (export, print, import) have disappeared...
- uninstall / remove goldfinch/image-editor and buttons reappear...

The same happens when social-media is installed (they have similar dependencies, so am guessing it's a dependency rather than the module itself):
https://github.com/goldfinch/social-media

**Comment by goldfinch** [comment]
#https://github.com/goldfinch/social-media/issues/2#issuecomment-2354362797
